[target.x86_64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-Wl,-rpath,@executable_path",
    "-C",
    "link-arg=-Wl,-rpath,@executable_path/../lib",
    "-C",
    "link-arg=-Wl,-rpath,/usr/local/opt/glfw/lib",
    "-C",
    "link-arg=-Wl,-rpath,/opt/homebrew/opt/glfw/lib",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-Wl,-rpath,@executable_path",
    "-C",
    "link-arg=-Wl,-rpath,@executable_path/../lib",
    "-C",
    "link-arg=-Wl,-rpath,/usr/local/opt/glfw/lib",
    "-C",
    "link-arg=-Wl,-rpath,/opt/homebrew/opt/glfw/lib",
]
